export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const POSTS_LIKED_SUCCESS = 'POSTS_LIKED_SUCCESS';

export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const UPDATE_POST_WITH_LIKE = 'UPDATE_POST_WITH_LIKE';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const POST_LOG_OUT = 'POST_LOG_OUT';

export const SHARE_POST_ERROR = 'SHARE_POST_ERROR';
export const SHARE_POST_MESSAGE = 'SHARE_POST_MESSAGE';
export const CLEAR_SHARE_POST_ERROR = 'CLEAR_SHARE_POST_ERROR';
export const CLEAR_SHARE_POST_MESSAGE = 'CLEAR_SHARE_POST_MESSAGE';

export const RECIEVE_PAGE_DATA = 'RECIEVE_PAGE_DATA';